spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm_second?useUnicode=true&characyerEncoding=uttf-8
    username: root
    password: zhou.1113
