#生产环境配置
server:
  port: 80
springdoc:
  api-docs:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  mail:
    host: smtp.163.com
    username: 15283340728@163.com
    password: UWNLIDNXVDSVSZDJ
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
    port: 5672
  datasource:
    url: jdbc:mysql://localhost:3306/elm_second?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhou.1113
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 10
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
